const productsDetails = [
  {
    id: 1,
    image: "../../imageFigma/supplements page/p1.jpg",
    desription: "GOLD STANDARD 100% WHEY is formulated for post-workout muscle support and recovery, and is widely used as an additional source of high quality protein in your main diet.Each serving of Optimum Nutrition's Whey Gold Standard Whey Protein contains 24 grams of high quality whey protein, predominantly from whey protein isolate, which has been cleared of excess carbohydrates, fat and lactose using sophisticated filtration techniques. ",
    buttonQat: " ",
    buttonAddCard: "Add card",
    buttonBuy: "Buy now",
    price: 70,
  },
  {
    id: 2,
    image: "../../imageFigma/supplements page/p2.jpg",
    desription: "LADY WHEY OT BIOPHARM is a unique product designed specifically for lovely ladies based on whey concentrate, isolate and hydrolyzate. Lady Whey is suitable for those who want to get rid of extra pounds, as well as maintain and restore their muscles after exhausting workouts.",
    buttonQat: " ",
    buttonAddCard: "Add card",
    buttonBuy: "Buy now",
    price: 15,
  },
  {
    id: 3,
    image: "../../imageFigma/supplements page/p3.jpg",
    desription: "Top Whey is an innovative product that contains in its composition the necessary components for the proper build-up of lean muscle mass, accelerated recovery after training, immune support and fat reduction. The protein matrix, consisting of quality whey protein concentrate and whey protein isolate, makes Top Whey bioavailable to the body.",
    buttonQat: " ",
    buttonAddCard: "Add card",
    buttonBuy: "Buy now",
    price:20,
  },
  {
    id: 4,
    image: "../../imageFigma/supplements page/p4.jpg",
    desription: "High quality flavored whey protein concentrate. Contains sweeteners.Whey protein is a high biological value protein source with an excellent amino acid profile. It is very quickly absorbed and supplies the body with essential amino acids.• Accelerates recovery after strenuous exercise• Highly bioavailable protein source• High quality ultra-filtered whey concentrate ",
    buttonQat: " ",
    buttonAddCard: "Add card",
    buttonBuy: "Buy now",
    price: 25,
  },
  {
    id: 5,
    image: "../../imageFigma/supplements page/p5.jpg",
    desription: "Whey Protein from Quamtrax is a whey protein concentrate that promotes accelerated anabolic growth of your muscles and more efficient recovery after training.It has already been proven that whey protein has an anabolic effect, that is, it enhances the action of anabolic hormones, which, as a result, leads to muscle growth.Once dissolved in water, Quamtrax's Direct Whey Protein passes quickly through the stomach and into the muscles in less than an hour! This makes it the best choice for a post-workout meal.",
    buttonQat: " ",
    buttonAddCard: "Add card",
    buttonBuy: "Buy now",
    price:25,
  },
  {
    id: 6,
    image: "../../imageFigma/supplements page/p6.jpg",
    desription: "FitMiss Delight is a unique, great-tasting, gluten-free protein supplement for women proven to satisfy hunger and support muscle mass. FitMiss Delight, containing plant-based protein SolaThin, helps fight thirst, making you feel fuller and faster, and promotes healthy digestion with digestive enzymes. In addition, FitMiss Delight offers nutrient-dense greens and superfoods that contain powerful vitamins and minerals to help support and maintain good health. FitMiss Delight is the obvious choice to support your health and fitness goals!",
    buttonQat: " ",
    buttonAddCard: "Add card",
    buttonBuy: "Buy now",
    price: 20.50,
  },
];
export default productsDetails;
